apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightctl-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: flightctl-ui
    role: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flightctl-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flightctl-ui
        role: frontend
    spec:
      containers:
        - env:
          - name: INTERNAL_OIDC_URL
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: INTERNAL_OIDC_URL
          - name: BASE_UI_URL
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: BASE_UI_URL
          - name: API_PORT
            value: '8080'
          - name: FLIGHTCTL_SERVER
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: FLIGHTCTL_SERVER
          - name: FLIGHTCTL_GRPC_SERVER
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: FLIGHTCTL_GRPC_SERVER
          - name: OIDC_INSECURE_SKIP_VERIFY
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: OIDC_INSECURE_SKIP_VERIFY
          - name: FLIGHTCTL_SERVER_INSECURE_SKIP_VERIFY
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: FLIGHTCTL_SERVER_INSECURE_SKIP_VERIFY
          - name: TLS_KEY
            value: /app/serving-cert/tls.key
          - name: TLS_CERT
            value: /app/serving-cert/tls.crt
          image: {{ .Values.image.image }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: flightctl-ui
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/certs
              name: flightctl-ui-certs
            - mountPath: /app/serving-cert
              name: flightctl-ui-serving-cert
      restartPolicy: Always
      volumes:
        - name: flightctl-ui-certs
          secret:
            secretName: flightctl-ui-certs
            items:
              - key: ca.crt
                path: ca.crt
              - key: ca_oidc.crt
                path: ca_oidc.crt
        - name: flightctl-ui-serving-cert
          secret:
            secretName: flightctl-ui-serving-cert
            defaultMode: 420