apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ui-from-router
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          policy-group.network.openshift.io/ingress: ""
      podSelector: {}
  podSelector:
    matchLabels:
      role: frontend
  policyTypes:
  - Ingress