kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: flightctl-ui
  namespace: {{ .Values.flightctlUi.namespace }}
  labels:
    external-exposed: 'true'
    paas.redhat.com/appcode: {{ .Values.appCode }}
    shard: external
spec:
  host: {{ .Values.flightctlUi.hostName }}
  to:
    kind: Service
    name: flightctl-ui
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    certificate: {{ .Values.flightctlUi.certs.frontRouter | quote }}
    key: {{ .Values.flightctlUi.certs.frontRouterKey | quote }}
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
    