apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ca.crt: {{ .Values.api.caCert | quote }}
  ca_oidc.crt: {{ default (.Values.global).auth.caCert .Values.auth.caCert | quote }}
