## @param image.image Image to deploy.
## @param image.tag Image tag to pull.
## @param image.pullPolicy K8s pull policy for pulling the image.
image:
  image: quay.io/flightctl/flightctl-ocp-ui
  pullPolicy: Always
  tag: ""
## @param api.url URL of Flightctl API endpoint accessible by UI backend.
## @param api.grpcUrl URL of Flightctl GRPC endpoint accessible by UI backend.
## @param api.insecureSkipTlsVerify Set to true if Flightctl TLS certificate validation should be skipped.
## @param api.caCert A custom CA cert for Flightctl TLS.
api:
  url: https://flightctl-api:3443/
  grpcUrl: grpcs://flightctl-api-agent-grpc:7444/
  insecureSkipTlsVerify: false
  caCert: ""

