apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: {{ .Values.keycloak.namespace }}
type: Opaque
stringData:
  DB_ADDR: {{ .Values.keycloak.db.dbAddr | quote }}
  DB_DATABSE: {{ .Values.keycloak.db.postgresqlDatabase | quote }}
  DB_PASSWORD: {{ .Values.keycloak.db.postgresqlPassword | quote }}
  DB_USER: {{ .Values.keycloak.db.postgresqlUser | quote }}
  DB_VENDOR: {{ .Values.keycloak.db.dbVendor | quote }}
  KEYCLOAK_ADMIN: {{ .Values.keycloak.keycloakAdmin | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.keycloakAdminPassword | quote }}