apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightctl-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: flightctl-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flightctl-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flightctl-ui
    spec:
      containers:
        - env:
          - name: API_PORT
            value: '8080'
          - name: FLIGHTCTL_SERVER
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: FLIGHTCTL_SERVER
          - name: FLIGHTCTL_GRPC_SERVER
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: FLIGHTCTL_GRPC_SERVER
          - name: FLIGHTCTL_SERVER_INSECURE_SKIP_VERIFY
            valueFrom:
              configMapKeyRef:
                name: flightctl-ui
                key: FLIGHTCTL_SERVER_INSECURE_SKIP_VERIFY
          - name: TLS_KEY
            value: /app/console-certs/tls.key
          - name: TLS_CERT
            value: /app/console-certs/tls.crt
          - name: IS_OCP_PLUGIN
            value: "true"
          image: {{ .Values.image.image }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: flightctl-ui
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: flightctl-ui-certs
              mountPath: /app/certs
            - name: console-serving-cert
              mountPath: /app/console-certs
      restartPolicy: Always
      volumes:
        - name: flightctl-ui-certs
          secret:
            secretName: flightctl-ui-certs
            items:
              - key: ca.crt
                path: ca.crt
            defaultMode: 420
        - name: console-serving-cert
          secret:
            secretName: console-serving-cert
            defaultMode: 420