kind: Service
apiVersion: v1
metadata:
  name: flightctl-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: flightctl-ui
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  selector:
    app: flightctl-ui
