apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flightctl-ui-from-ingress 
  namespace:  {{ .Release.Namespace }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  podSelector:
    matchLabels:
      app: flightctl-ui 
  policyTypes:
  - Ingress
